params = {
    'seed': 123456789,
    'lr': 1e-3,
    'batch_size': 32,
    'test_batch_size': 32,
    'optimizer': 'momentum',
    'epochs': 10,
    'wd': 1e-5,
    'scheduler_eta_min': 3e-6,
    'model_name': 'timm/eca_nfnet_l1',
    'pooling': 'GeM',
    'class_topk': 9691,
    'use_fc': True,
    'use_prelue': True,
    'loss': 'arcface',
    'margin': 0.3,
    's': 30,
    'theta_zero': 1.25,
    'fc_dim': 512,
    'scale_limit': 0.2,
    'shear_limit': 0,
    'brightness_limit': 0.0,
    'contrast_limit': 0.0,
    'augmentation': 'soft',
    'train_data': 'gld_v1',
    'test_size': 0.01,
    'image_size': (288, 288)
}
