FROM python:3.9

RUN apt-get update \
    && apt-get install -y libboost-dev
RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y

RUN pip3 install --upgrade pip
COPY requirements-spotty.txt requirements-spotty.txt
RUN pip3 install -r requirements-spotty.txt